---
title: "547 class 1"
author: "Emily West"
date: "10/24/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#R for strings
```{r}
Strings have special characters
```


```{r}
# a string refers to character data, to make a string surround it by quotes
my_string <- "Anything surrounded by quotes."
#double quotes allow you to use single quotes inside without  breaking the string
my_string

#whatever quote (double or single) you use to open the string, use the other quote inside of the string without breaking the string
#when choosing a delimiter do not use that character inside the string
my_string2 <- 'This is another string containing "double quotes".'
my_string2

my_string3 <- "a slash \ " #slash doesnot get read beacause it is used to escape a special character, to overcome this you add another slash
my_string3
my_string4 <- "a slash \\ " #kind of, now printing both slashes


```

###Homework
"How do I "string" a single slash?
```{r}
my_string4 <- `my_string`
my_string5 <- 'my_string'
my_string4 == my_string5
my_string6 <- "my_string"

my_string5 == my_string6 #why are single to double the same but single to back quotes return different objects? Back quotes deliminates the name of an object

```

# A new toolset to work with
```{r}
devtools::install_github("joeybernhardt/singer")
library(singer)
places<- unique(singer_locations$city) #no repeat cities, no duplicates
str(places)
ncahr() #takes a vector of strings and returns the length of their names
nchar(c("City", "double", "a very long string"))
nchar(c("",NA," ", "       ")) #nchar counts the number of characters including white spaces
# you can trim white space during import with trim = , however sometimes whitespace is used as a seperator and should be retained
nchar(c("",NA," ", "       ", "\t"))

```

#Tools of the trade
```{r}
#install.packages("glue")
#devtools::install_github("tidyverse/singer")
#devtools::install_github("tidyverse/glue")
#from tidyverse
library(tidyverse)
library(stringr)
library(glue)
```


```{r}
paste() #base r choice for glueing two strings together, "boring syntax"
glue() #sticks together strings and special r objects; like paste but on steroids

my_name <- "Emily"
my_age <- 148
my_color <- "green"

glue("My name is {my_name}") #uses curly bracket to call the object you are glueing, curly brackets will be converted to a string
paste("My name is", my_name, "My age was", my_age - 2) #difference is in syntax

glue("My name is {my_name}, My age two years ago was {my_age - 2}.")

glue("
My name is 
  {my_name}, 
My age two years ago was 
  {my_age - 2}") #will retain indentations

glue("
My name is 
  {my_name}, 
My age two years ago was 
  {my_age - 2}." ,
my_name = "Another Name", my_age = 10)
```

#Challenge
Phrase: Today is Wednesday, October 29, 1986, and the sun shines
Get date from R: Sys.Date()
Use glue to paste Sys.Date() in phrase
```{r}
date <- Sys.Date()
my_phrase <- glue("Today is {date} and the sun shines")
my_phrase #Wahooo did it on my own!
#define on the fly in clue
my_phrase <- glue("Today is {date} and the sun shines",
                  date = Sys.Date())
#don't want to continuously write phrase out:
phrase<-"Today is {date} and the sun shines"
glue(phrase, day = Sys.Date())
#define the format:
glue(phrase, day = format(Sys.Date(), "%A, %B, %d, %Y")) #A , B, D number of day, Y year
```

'glue_data'
```{r}
#pull data out of a dataframe:
singer_locations %>% 
  glue_data("{artist_name} is from {city}.") %>% 
  head()
```

#Stringer
```{r}
getNamespaceExports("stringr") # get the functions offered by stringr
```

```{r}
getNamespaceExports("stringr") %>% str_view("str_") #string view highlights everything with a pattern

getNamespaceExports("stringr") %>% str_subset("str_") #keep all with a positive match from stringr that start with str_
```

#Challenge
```{r}
places <-unique(singer_locations$city)
head(places)

#get all the places containing the string "york"
places %>% str_subset("york") # case sensitive, only picking up lowercase y

places %>% str_to_lower() %>% 
  str_subset("york") #picks up upper and lower case y by changing everything to lower

```

#Regular expression, shorthanding based on patterns in a string
```{r}
places %>% 
  str_subset("[Yy]ork") #whatever inside square brackets can be a positive match

places %>% 
  str_subset(coll("york", ignore_case = TRUE)) #coll allows you to define arguments

places %>% 
  str_subset("York$") #$ a special character that indicats that York must be at the end of the string, omitt Yorkshire

places %>% 
  str_subset("^York") # ^ start with York
```

#Challenge
```{r}
#Get all places containing some digits
"[:digit:]"

places %>% 
  str_subset("[:digit:]")

places %>% 
  str_subset("B.a") #contain B and a 

places %>% 
  str_subset("B.a?") #Must have a B but may or may not have an a after

places %>% 
  str_subset("B.a2") 

places %>% 
  str_subset("B.a*") # * zero 1 or more occurrence of that character

places %>% 
  str_subset("[Nn]ew [Yy]ork")

```

