---
title: "Homework 9 Reflection"
author: "Emily West"
date: "11/28/2017"
output: html_document
---

Hello there and welcome to my very first package!

Admittedly, naming a package [hw09](https://github.com/emwest/stat547HW09) is not very inspired, but you get the gist, click on the link to be taken to my r package!

Description: I decided to build a package that allows the user to visualize the output from a linear model in a very quick and easy way, using the tidy() and qplot() functions. For reference, one should be careful when relying heavily on other non-base r packages. This runs the risk of development changes making your package, or functions contained within, unusable in the future. But because this is something I am doing a lot (inspecting lms) this type of function is actually really useful to me!

In developing this package I followed these steps:

:star: create a unique, (somewhat) helpful function

:star: document the function using roxygen2

:star: added an accompanying dataset so the user (or peer review) can test out my package

:star: update the description file to include the developer, brief package description, and package dependencies 

:star: update the licensing information so others can use my package without worry, this includes making a new file in the project repository called LICENSE

:star: create a test file that assures the function actually works

:star: Update the vignette file that will accompany my package with useful and necessary information for the user

Reflection: Like voting, I checked and tested my functions early and often. This is a much easier way to find and address errors than waiting until they pile up to address them. Interestingly, I had few errors but several warnings which were more often than not associated with poor documentation. I did my best to alleviate these warnings, however R likes to warn you that it is constantly being updated, so this package relies on R version X.X.X and on packages x,y,z which are actually probably good warnings to keep around in the long run.

I returned to my package to make a few tweeks and learned that can be a terrible idea if you have it working smoothly. It seems the smallest change can lead to some unintended consequences. For instance, I tried to add a load message with my package however, it seems like it threw everything off and my package would not pass the check without errors. This underscores the need for intention when developing and making changes to a package. 
