##run my scripts	
source("/Users/Adelaide/Desktop/UBC_Work/STAT545/stat547/hw07/download.R")
source("/Users/Adelaide/Desktop/UBC_Work/STAT545/stat547/hw07/prelim_analysis.R")
source("/Users/Adelaide/Desktop/UBC_Work/STAT545/stat547/hw07/stats.R")